fulltest/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('website.urls')),
]

website/urls.py
from django.conf.urls import url
from . import views

app_name = 'website'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<post_id>[0-9]+)/$', views.post_detail, name='post-detail'),
    url(r'^post/$', views.create_post, name='post-create'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^register/$', views.register_user, name='register'),
    url(r'^(?P<post_id>[0-9]+)/comment/$', views.create_comment, name='comment-add'),
    url(r'^(?P<post_id>[0-9]+)/comment/(?P<comment_id>[0-9]+)/reply/$', views.reply_comment, name='comment-reply'),
    url(r'^activate/(?P<activation_code>\w+)/$', views.activate_user, name='user-activate'),
    url(r'^success/$', views.register_success, name='register-success'),
    url(r'^upvote/$', views.upvote, name='upvote')
]

website/models.py
from django.db import models
from customauth.models import MyUser


# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(MyUser)
    content = models.TextField(max_length=10000)
    upvotes = models.ManyToManyField(MyUser, blank=True, related_name='postUpvotes')
    downvotes = models.ManyToManyField(MyUser, blank=True, related_name='postDownvotes')
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.author.get_full_name() + " - " + self.title


class Comment(models.Model):
    author = models.ForeignKey(MyUser)
    post = models.ForeignKey(BlogPost)
    content = models.TextField(max_length=1000)
    parent = models.ForeignKey('self', null=True, blank=True)

    def __str__(self):
        return self.content
        

website/forms.py
from django import forms
from .models import BlogPost, Comment
from customauth.models import MyUser


class PostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ['title', 'content']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content']


class UserForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = MyUser
        fields = ['username', 'email', 'password']


class UpvoteForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        # exclude = ['author', 'updated', 'created', ]
        fields = []

website/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import logout, authenticate, login
from django.utils.crypto import get_random_string
from django.core.mail import send_mail
from django.template.loader import render_to_string

from .models import BlogPost, Comment
from .forms import PostForm, CommentForm
from .admin import UserCreationForm
from customauth.models import MyUser



# Create your views here.
def index(request):
    return render(request, 'website/index.html', {'blogs': BlogPost.objects.all()})


def post_detail(request, post_id):
    post = BlogPost.objects.get(pk=post_id)
    return render(request, 'website/post_detail.html', {'post': post})


def create_post(request):
    if not request.user.is_authenticated():
        return redirect('website:login')
    else:
        form = PostForm(request.POST or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('website:post-detail', post_id=post.pk)
        context = {
            "form": form,
        }
        return render(request, 'website/create_post.html', context)


def user_logout(request):
    logout(request)
    return redirect('website:index')


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_activated:
                login(request, user)
                return redirect('website:index')
            else:
                return render(request, 'website/login.html', {'error_message': 'You must activate your account before logging in'})
        else:
            return render(request, 'website/login.html', {'error_message': 'Invalid login'})
    return render(request, 'website/login.html')


def register_user(request):
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        user.activation_code = generate_activation_url()
        user.save()

        # generate email
        msg_plain = 'hi'
        msg_html = render_to_string('website/activate.html', {'user': user, 'code': user.activation_code})
        send_mail('Activate Acount', msg_plain, 'chasevedder@gmail.com', [user.email,], html_message=msg_html)

        password = request.POST['password2']
        username = user.email
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('website:index')

        return redirect('website:register-success')
    context = {
        "form": form,
    }
    return render(request, 'website/register.html', context)


def create_comment(request, post_id):
    if not request.user.is_authenticated():
        return redirect('website:login')
    else:
        form = CommentForm(request.POST or None)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = BlogPost.objects.get(pk=post_id)
            comment.author = request.user

            comment.save()
            return redirect('website:post-detail', post_id=post_id)
        context = {
            "form": form,
            "post": BlogPost.objects.get(pk=post_id)
        }
        return render(request, 'website/create_comment.html', context)


def reply_comment(request, post_id, comment_id):
    if not request.user.is_authenticated():
        return redirect('website:login')
    else:
        form = CommentForm(request.POST or None)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.parent = Comment.objects.get(pk=comment_id)
            comment.post = comment.parent.post
            comment.author = request.user

            comment.save()
            return redirect('website:post-detail', post_id=post_id)
        context = {
            "form": form,
            "post": BlogPost.objects.get(pk=post_id),
            "comment": Comment.objects.get(pk=comment_id)
        }
        return render(request, 'website/create_comment.html', context)


def generate_activation_url():
    code = get_random_string(32)
    try:
        user = MyUser.objects.get(activation_code=code)
    except MyUser.DoesNotExist:
        return code
    return generate_activation_url()


def activate_user(request, activation_code):
    try:
        user = MyUser.objects.get(activation_code=activation_code)
        user.is_activated = True
        user.save()
        return render(request, 'website/user_activated.html')
    except MyUser.DoesNotExist:
        return redirect('website:register')


def register_success(request):
    return render(request, 'website/account_creation_success.html', {})


def upvote(request):
    post_id = request.POST.get('post_id')
    vote_type = request.POST.get('type')
    action = request.POST.get('action')

    post = get_object_or_404(BlogPost, pk=post_id)

    upvotes = post.upvotes.filter(id=request.user.id).count()
    downvotes = post.downvotes.filter(id=request.user.id).count()

    if action == 'vote':
            if vote_type == 'up':
                post.upvotes.add(request.user)
                post.downvotes.remove(request.user)
            elif vote_type == 'down':
                post.upvotes.remove(request.user)
                post.downvotes.add(request.user)
            else:
                return HttpResponse('500 - unknown vote type' + vote_type)
    elif action == 'recall-vote':
        if vote_type == 'up':
            post.upvotes.remove(request.user)
        elif vote_type == 'down':
            post.downvotes.remove(request.user)
        else:
            return HttpResponse('500 - unknown vote type or no vote to recall' + vote_type)
    else:
        return HttpResponse('500 - bad action')
    post.score = post.upvotes.count() - post.downvotes.count()
    post.save()
    return HttpResponse(post.score)

website/templates/website/account_creation_success.html
{% extends 'website/base.html' %}

{% block body %}
<div class="container-fluid">
    <h1>Success!</h1>
    <h4>Check your email for an activation link.</h4>
    <a href="{% url 'website:login' %}">Click here to login</a>
</div>
{% endblock %}

website/templates/website/activate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Hello, {{ user.username }}</h1>
    <p><a href="chasevedder.xyz{% url 'website:user-activate' code %}">Click Here</a>in order to activate your account.</p>
</body>
</html>

website/templates/website/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Chase{% endblock %}</title>
    {% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'website/style.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'website/main.js' %}"></script>
    {% block head %}
    {% endblock %}


</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'website:index' %}">Chase</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">


            <ul class="nav navbar-nav navbar-right">

                {% if request.user.is_authenticated %}
                <li class="">
                    <a href="{% url 'website:post-create' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Post
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'website:logout' %}">
                        <span class = "glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
                {% else %}
                <li class="">
                    <a href="{% url 'website:register' %}">
                        <span class = "glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Register
                    </a>
                </li>
                    <li class="">
                    <a href="{% url 'website:login' %}">
                        <span class = "glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Sign in
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

website/templates/website/comment_template.html
<div class="test" style="margin-top: 15px">

    <div class="panel panel-default" style="margin-bottom: -10px">
        <div class="panel-body">
            <ul>
                <li style="margin-left: -30px;list-style: none;">
                    <span>{{ comment.content }}</span><br>
                    <span class="small" style="font-size: 10px">{{ comment.author.username }} - <a href="{% url 'website:comment-reply' comment.post.pk comment.pk %}">reply</a> </span>
                    {% for ch in comment.comment_set.all %}
                        {% with comment=ch template_name='website/comment_template.html' %}
                            {% include template_name %}
                        {% endwith %}
                    {% endfor %}
                </li>
            </ul>
        </div>
    </div>
</div>

website/templates/website/create_comment.html
{% extends 'website/base.html' %}

{% block body %}
<div class="container-fluid">
    <div class="post-detail" style="margin-bottom: 20px">
        <h1>{{ post.title }}</h1>
        <span>{{ post.content }}</span>
    </div>
    {% if comment %}

    <div class="panel panel-default">
        <div class="panel-body">
            <ul>
                <li style="margin-left: -30px;list-style: none;">
                    <span>{{ comment.content }}</span><br>
                    <span class="small" style="font-size: 10px">{{ comment.author.username }}</span>
                </li>
            </ul>
        </div>
    </div>

    {% endif %}
    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>
                        {% if comment %}
                        Reply
                        {% else %}
                        Comment on a post
                        {% endif %}
                    </h3>
                </div>
                <div class="panel-body">

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'website/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/website/create_post.html
{% extends 'website/base.html' %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a post</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'website/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

</div>
{% endblock %}

website/templates/website/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-12">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

website/templates/website/index.html
{% extends 'website/base.html' %}

{% block head %}
<script>
$(document).ready(function() {

    $('img.vote-up').click(function() {
        var post_id = $(this).attr('id').replace('up-', '');
        var idk = $(this);
        var vote_type = 'up';

        if ($(this).hasClass('selected')) {
            var vote_action = 'recall-vote';
            $.post('upvote/', {post_id:post_id, type:vote_type, action:vote_action}, function(response) {
                console.log(response);
                $('#upvotes-' + post_id).html(response);
                $('#up-' + post_id).attr('class', 'vote-up');
            });
        } else {

            var vote_action = 'vote';
            $.post('/upvote/', {post_id:post_id, type:vote_type, action:vote_action}, function(response) {
                console.log(response);
                $('#upvotes-' + post_id).html(response);
                $('#up-' + post_id).attr('class', 'vote-up selected');
                $('#down-' + post_id).attr('class', 'vote-down');
                var style = $('#up-' + post_id).attr('style')
                $('#up-' + post_id).attr('style', style + 'background-color: green;');
            });
        }
    });

    $('img.vote-down').click(function() {
        var post_id = $(this).attr('id').replace('down-', '');
        var idk = $(this);
        var vote_type = 'down';

        if ($(this).hasClass('selected')) {
            var vote_action = 'recall-vote';
            $.post('upvote/', {post_id:post_id, type:vote_type, action:vote_action}, function(response) {
                $('#upvotes-' + post_id).html(response);
                $('#down-' + post_id).attr('class', 'vote-down');
            });
        } else {

            var vote_action = 'vote';
            $.post('/upvote/', {post_id:post_id, type:vote_type, action:vote_action}, function(response) {
                console.log(response);
                $('#upvotes-' + post_id).html(response);
                $('#up-' + post_id).attr('class', 'vote-up');
                $('#down-' + post_id).attr('class', 'vote-down selected');
                var style = $('#down-' + post_id).attr('style')
                $('#down-' + post_id).attr('style', style + 'background-color: green');
            });
        }
    });
});
    </script>
{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="col-sm-12">
        {% for blog in blogs %}
            <table class="col-sm-12">
                <tbody>
                <tr>
                    <td style="width:10px;">
                        <table>
                            <tbody id="post-{{ blog.id }}">
                            <tr style="margin-bottom: 10px;">
                                <td align="center">
                                    <img class="vote-up" id="up-{{ blog.id }}" src = "http://i.imgur.com/nFn8U6a.png" style="width:20px; height:20px;" title="Vote this thread UP. (click again to undo)" />


                                </td>
                            </tr>
                            <tr>
                                <td align="center" id="upvotes-{{ blog.id }}">{{ blog.score }}</td>
                            </tr>
                            <tr>
                                <td align="center">
                                    <img class="vote-down" id="down-{{ blog.id }}" src = "http://i.imgur.com/Zh8gUCt.png" style="width:20px; height:20px;" title="Vote this thread DOWN if it is innapropriate or incorrect. (click again to undo)" />

                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </td>
                    <td>
                        <div class="panel panel-default" style="margin-top: 20px">
                            <div class="post panel-body">
                                <a href="{% url 'website:post-detail' blog.pk %}">
                                    <h4 style="margin: -5px; margin-left:5px">{{ blog.title }}</h4>
                                </a>
                            </div>
                            <div class="panel-footer">
                                <span class="small">Submitted by {{ blog.author.username }}</span>
                            </div>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        {% endfor %}
    </div>
</div>
{% endblock %}

website/templates/website/login.html
{% extends 'website/base.html' %}
{% block body %}
<div class="container-fluid">

{% include 'website/login_template.html' %}

</div>

{% endblock %}

website/templates/website/login_template.html
<div class="row">
    <div class="col-sm-12 col-md-6">
        <div class="panel panel-default">
            <div class="panel-body">
                <h3>Log In</h3>
                {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                {% endif %}
                <form class="form-horizontal" role="form" action="{% url 'website:login'%}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="id_username">
                            Username:
                        </label>
                        <div class="col-sm-10">
                            <input id="id_username" maxlength="30" name="username" type="text">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="id_password">
                            Password:
                        </label>
                        <div class="col-sm-10">
                            <input id="id_password" maxlength="30" name="password" type="password">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Login</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="panel-footer">
                Don't have an account? <a href="#">Click here</a> to register.
            </div>
        </div>
    </div>
</div>

website/templates/website/post_detail.html
{% extends 'website/base.html' %}

{% block body %}
    <div class="container-fluid">
        <div class="panel panel-default" style="margin-bottom: 20px; padding-bottom: 0px;">
            <div class="panel-body">
                <h3>{{ post.title }}</h3>
            </div>
            <div class="panel panel-default" style="margin-top: -20px; margin-bottom: 0px; border-radius: 0px">
                <div class="panel-body">
                    <span>{{ post.content }}</span>
                </div>
            </div>

        </div>
        <h2>Comments</h2> &nbsp;
        <a href="{% url 'website:comment-add' post.pk%}">Add a comment</a>
        {% for comment in post.comment_set.all %}
            {% if not comment.parent %}
                {% include 'website/comment_template.html' %}
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

website/templates/website/register.html
{% extends 'website/base.html' %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'website/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'website:login' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

website/templates/website/user_activated.html
{% extends 'website/base.html' %}

{% block body %}
<div class="container-fluid">
    <h1>Successfully Activated Account!</h1>
    <h4>Login to continue</h4>
    {% include 'website/login_template.html' %}
</div>
{% endblock %}